from aiogram.fsm.state import State, StatesGroup


class PaymentStates(StatesGroup):
    choose_manager = State()
    choose_month = State()
    choose_category = State()
    choose_license = State()
    enter_client = State()
    enter_qty = State()
    choose_period = State()
    choose_package = State()
    choose_payment_date = State()
    enter_payment_date = State()
    confirm_price = State()
    enter_price = State()
    confirm_fact = State()
    enter_amount = State()
    choose_bank = State()
    enter_fact = State()
    choose_start_month = State()
    choose_activation = State()
    choose_act_period = State()
    confirm = State()
    upload_receipt = State()
    enter_manual_amount = State()
    choose_bot_period = State()
    enter_bot_amount = State()
    ask_add_service = State()
    choose_service_category = State()
    choose_service_bank = State()  # 21.07.2026: услуги оплачивают в другой банк
